---
basic_packages:
  Debian:
    - vim
    - git
    - curl
    - wget
    - unzip
    - htop
    - net-tools
    - jq
    - python3
    - python3-requests
  Archlinux:
    - vim
    - git
    - curl
    - wget
    - unzip
    - htop
    - inetutils # provides netstat
    - jq
    - python
    - python-requests
