---
TIMEZONE: Asia/Kolkatta
ENABLE_IPV6: "true"
DNS_LISTENING_MODE: "all"
DNS_UPSTREAMS: "8.8.8.8;8.8.4.4"
DHCP_ACTIVE: "true"
PIHOLE_CONTAINER: pihole/pihole:latest
DHCP_START: 192.168.86.40
DHCP_END: 192.168.86.250
DHCP_ROUTER: 192.168.86.1
